name: Update Cloudflare DNS with IPv4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install node Packages
      run: npm install express node-pty fs ws

    - name: Install Warp client
      run: |
        sudo apt update
        curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ bookworm main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
        sudo apt-get update && sudo apt-get install cloudflare-warp

    - name: Register and Connect Warp
      run: |
        echo | sudo warp-cli register --accept-tos
        sudo warp-cli connect

    - name: Capture Public IPv4
      run: |
        PUBLIC_IPV4=$(curl -s http://checkip.amazonaws.com)
        echo "PUBLIC_IPV4=$PUBLIC_IPV4" >> $GITHUB_ENV

    - name: Start server
      run: |
        node server.js &
        sleep 5  # Give the server some time to start

    - name: Update Cloudflare DNS with IPv4
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.DNS_RECORD_ID }}" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data '{"type":"A","name":"futureprojects.cloudns.org","content":"'"${{ env.PUBLIC_IPV4 }}"'","proxied":true,"ttl":120}'
