name: Build and Run Blazor Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'  # Replace with a version that supports .NET 7.0

      - name: Build and Test
        run: |
          cd YourBlazorProjectName
          dotnet build -c Release
          dotnet test

      - name: Run Blazor Application
        run: |
          cd YourBlazorProjectName
          dotnet run
