name: Update Cloudflare DNS with IPv4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install node Packages
      run: npm install express node-pty fs ws

    - name: Install Warp client
      run: |
        sudo apt install cloudflare-warp
        warp-cli registration new
        warp-cli connect

    - name: Start server
      run: |
        node server.js &
        sleep 5  # Give the server some time to start

    - name: Update Cloudflare DNS with IPv4
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.DNS_RECORD_ID }}" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data '{"type":"A","name":"futureprojects.cloudns.org","content":"'"${{ env.PUBLIC_IPV4 }}"'","proxied":true,"ttl":120}'
