name: Setup Cloudflare Tunnel for RDP

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch

jobs:
  setup-tunnel:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
  
      - name: Install Express, node-pty, ws and fs 
        run: |
          npm install express node-pty ws fs

      - name: Install Cloudflared
        run: |
          sudo apt-get update
          sudo ufw allow 3000/tcp
          sudo ufw reload

      - name: Retrieve Public IPv4 and IPv6 addresses
        id: get-public-ips
        run: |
          IPv4=$(curl -s https://ipinfo.io/ip)
          IPv6=$(curl -s https://api64.ipify.org)
          echo "Public IPv4: $IPv4"
          echo "Public IPv6: $IPv6"
          echo "PUBLIC_IPV4=$IPv4" >> $GITHUB_ENV 
          echo "PUBLIC_IPV6=$IPv6" >> $GITHUB_ENV

      - name: Run Express server
        run: |
          nohup node server.js 

     
