name: Setup Cloudflare Tunnel for RDP

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch

jobs:
  setup-tunnel:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
 
      - name: Install Express, node-pty, and ws 
        run: |
          npm install express node-pty ws

      - name: Running Websocket
        run: sudo node websocket.js
